### ISSUE TITLE
[Feature]: CRD Versions Management

### ISSUE THREAD

**Issue by iGxnon** [xline-kv/xline-operator#21]
### Description about the feature

It will be a good enhancement if the operator could automatically perform migration from old versions to latest.

When multiple versions are applied to the k8s cluster, conflicts arise with [Kubernetes CRD regulations](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition) because the subsequent version also has the `storage: true` setting.

### Current Version

If we try to apply a higher version of CRD, the operator will panic and refuse to start.

```shell
2023-08-07T12:00:09.337960Z DEBUG kube_client::client: Unsuccessful: ErrorResponse { status: "Failure", message: "CustomResourceDefinition.apiextensions.k8s.io \"xlineclusters.xlineoperator.xline.cloud\" is invalid: status.storedVersions[0]: Invalid value: \"v1alpha\": must appear in spec.versions", reason: "Invalid", code: 422 }
Error: ApiError: CustomResourceDefinition.apiextensions.k8s.io "xlineclusters.xlineoperator.xline.cloud" is invalid: status.storedVersions[0]: Invalid value: "v1alpha": must appear in spec.versions: Invalid (ErrorResponse { status: "Failure", message: "CustomResourceDefinition.apiextensions.k8s.io \"xlineclusters.xlineoperator.xline.cloud\" is invalid: status.storedVersions[0]: Invalid value: \"v1alpha\": must appear in spec.versions", reason: "Invalid", code: 422 })

Caused by:
    CustomResourceDefinition.apiextensions.k8s.io "xlineclusters.xlineoperator.xline.cloud" is invalid: status.storedVersions[0]: Invalid value: "v1alpha": must appear in spec.versions: Invalid
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iGxnon** [comment]
We need to use `kube::core::crd::merge_crds` to merge multiple versions or set the stored version to the latest by first patching down the previous stored version and then patch the latest version.

**Comment by iGxnon** [comment]
1. We should ensure that CRDs are backward compatible so that we can select the latest version as the stored version when merging CRDs.
2. When a breaking change occurs in CRD, we should not directly set the stored version to the latest one. This could potentially lead to inconsistent in the currently running CRs. We should ensure that all CRs are at the latest version before setting the stored value of the latest version to true.

**Comment by liangyuanpeng** [comment]
This is more of a feature or enhancement and not a bug. This is a problem that every operator needs to working for it.

**Comment by iGxnon** [comment]
> This is more of a feature or enhancement and not a bug. This is a problem that every operator needs to working for it.

Thx, I'll change the title

**Comment by liangyuanpeng** [comment]
After a quick read of the project, I probably understand your motivation. I think https://github.com/xline-kv/xline-operator/tree/main/operator-k8s/src/crd/v1alpha can be removed, it may be a wrong version, the correct one is v1alpha1.

WDYT @iGxnon

**Comment by iGxnon** [comment]
> After a quick read of the project, ~I probably understand your motivation. I think https://github.com/xline-kv/xline-operator/tree/main/operator-k8s/src/crd/v1alpha can be removed, it may be a wrong version, the correct one is v1alpha1.~
> 
> WDYT @iGxnon
> 
> https://github.com/xline-kv/xline-operator/blob/f3000b76a0e560226e81c855e170fe96f7870673/operator-k8s/src/crd/mod.rs#L1-L12
> 
> Seems like it's the right thing.

Not a big problem. As the `alpha` version is not quit stable, I plan to delete all previous `alpha` versions after releasing a new `alpha`/`beta`/`stable` version.
