### ISSUE TITLE
[Feature]:  public access for CRD struct

### ISSUE THREAD

**Issue by liangyuanpeng** [xline-kv/xline-operator#32]
### Description about the feature

Wee need to allow users to operate crd resources outside xline-operator (for example, create xline cluster), which means that the struct corresponding to operator crd should be publicly accessible, currently within the crate scope.

https://github.com/xline-kv/xline-operator/blob/1a15e69438eb46becf752a4de362627890e1e26b/operator-k8s/src/crd/v1alpha1/cluster.rs#L31-L33

This is a good first issue for me,  i want to work for it and assign me please,Thanks. Remind me if i missed something.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iGxnon** [comment]
Should xline-operator be used as a binary, so there is no need to provide a public CRD definition as a library?

**Comment by liangyuanpeng** [comment]
Absolutely, xline-operator run as a binary,  At the same time, the CRD definition should also be provided as a libiary so that others can use it. 

Let user can apply CR with rust code and not kubectl for integration into their platform.

**Comment by iGxnon** [comment]
> Absolutely, xline-operator run as a binary, At the same time, the CRD definition should also be provided as a libiary so that others can use it.
> 
> Let user can apply CR with rust code and not kubectl for integration into their platform.

That makes sense, I suggest move these CRDs into a separated crate.

**Comment by liangyuanpeng** [comment]
>  I suggest move these CRDs into a separated crate.

@iGxnon ,How about `xline-operator-api`, I thought this might cause some confusion given that the `operator-api` crate already exists.

**Comment by iGxnon** [comment]
> > I suggest move these CRDs into a separated crate.
> 
> @iGxnon ,How about `xline-operator-api`, I thought this might cause some confusion given that the `operator-api` crate already exists.

`operator-api` is used to reduce the coupling between operator and sidecar. A simple name crd-api might be sufficient

**Comment by iGxnon** [comment]
I'll handle this in #37

**Comment by liangyuanpeng** [comment]
This is not need any more due to the xline-operator is rewriting with golang.

closing...
